project:
  type: website

website:
  description: "The Austronesian Circle is a discussion group hosted by the Department of Linguistics at the University of Hawai‘i at Mānoa."
  # navbar:
  #   right:
  #     - about.qmd
      
format:
  html:
    theme: yeti
    css: styles.css



