---
title: "An enhancing of reo magareva (Mangarevan, language from French Polynesia): The project of « bilingual teaching French-Mangarevan » (for cycles 1, 2 and 3)"
author: "Albert Hugues"
date: "2023-04-14"
categories: [Mangarevan, Polynesian, education]
---

The reo magareva is the vernacular language of the Mangareva (or Gambier) archipelago and is notably an overseas regional language after Tahitian in French Polynesia.  French is the official language. According to the latest studies, the reo magareva is a "severely endangered" language (Ena Manuireva ; 2015). Nowadays, the Ministry of Education has decided to set up a bilingual French-Mangarevan teaching system with equal hours at the Maputeoa elementary school from the beginning of the school year in August 2021 (cycle 1 only) in an effort to raise awareness of the heritage, decentralize the frameworks and give priority to the academic success of the pupils. Today, since August 2022, the unanimous choice of the teaching staff is to extend the scheme to the three levels: cycles 1 (kindergarten), 2 (1st-3rd grade) and 3 (4th-6th grade). 
 
The results of this thesis will enable us to understand the sociolinguistic changes that have occurred since the emergence of the project. The latter influences teachers, children, parents and inhabitants, in other words the whole linguistic community of the archipelago. At on social level, the system is creating a stream of consciousness within families. The relatives want to learn; some learn new words, some are against the neologisms of the school... We will analyze their feelings and actions towards the project. Then, on the linguistic level, we will observe the oxymoronic creation between the enhancing of old words and the creation of new terms by the agent. The transmission of these lexicons among the pupils is also the object of our study within and outside the school when the community is deprived of an academy. We will extract the results of this research from the semi-structured interviews. This work will allow us to account for the various ways in which reo magareva is valued through the project.